# Generated by Django 5.1.4 on 2025-01-06 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('userType', models.CharField(choices=[('0', 'أب'), ('1', 'ابن'), ('2', 'مدير النظام')], max_length=10, verbose_name='نوع المستخدم')),
                ('gender', models.CharField(choices=[('1', 'ذكر'), ('2', 'انثى')], default='1', max_length=10, verbose_name='الجنس')),
                ('first_name', models.CharField(max_length=30, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=30, verbose_name='الاسم الأخير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='موظف')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدمين',
                'verbose_name_plural': 'المستخدمين',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildUser', models.OneToOneField(limit_choices_to={'userType': '1'}, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='اختر الابن')),
                ('FatherUser', models.ForeignKey(blank=True, limit_choices_to={'userType': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_user', to=settings.AUTH_USER_MODEL, verbose_name='الأب')),
            ],
            options={
                'verbose_name': 'طفل',
                'verbose_name_plural': 'الاطفال',
            },
        ),
        migrations.CreateModel(
            name='MostUseApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=20, verbose_name='اسم التطبيق')),
                ('hour', models.TimeField(verbose_name='ساعات الاستخدام')),
                ('ChildUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child', verbose_name='الابن')),
            ],
            options={
                'verbose_name': 'تطبيق اكثر استخدام',
                'verbose_name_plural': 'التطبيقات الاكثر استخدام',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfNotification', models.DateField(default=django.utils.timezone.now, verbose_name='وقت حدوث البلاغ')),
                ('imageOfNotification', models.ImageField(max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/', verbose_name='صورة البلاغ')),
                ('ChildUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child', verbose_name='الابن')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
            },
        ),
    ]
