# Generated by Django 5.1.4 on 2025-01-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(default='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/guest-user.webp', max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/', verbose_name='صورة الملف الشخصي'),
        ),
    ]
