# Generated by Django 5.1.4 on 2025-01-08 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ChildUser',
            field=models.OneToOneField(blank=True, limit_choices_to={'userType': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='اختر الابن'),
        ),
    ]
