# Generated by Django 5.1.4 on 2025-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_child_childuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
