# Generated by Django 5.1.5 on 2025-02-06 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_child_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(default='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/guest-user.webp', max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/2025-02-07/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='imageOfNotification',
            field=models.ImageField(max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/2025-02-07/', verbose_name='صورة البلاغ'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
