# Generated by Django 5.1.5 on 2025-03-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'اشعار', 'verbose_name_plural': 'اشعارات'},
        ),
        migrations.AddField(
            model_name='mostuseapps',
            name='imageOfApp',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/appsIcon/2025-03-03/', verbose_name='ايقونة التطبيق'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(default='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/guest-user.webp', max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/2025-03-03/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='imageOfNotification',
            field=models.ImageField(max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/2025-03-03/', verbose_name='صورة البلاغ'),
        ),
    ]
