# Generated by Django 5.1.5 on 2025-03-08 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_options_mostuseapps_imageofapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ChildUser',
            field=models.ForeignKey(blank=True, limit_choices_to={'userType': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='اختر الابن'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(default='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/guest-user.webp', max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/profileImages/2025-03-08/', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='mostuseapps',
            name='imageOfApp',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/appsIcon/2025-03-08/', verbose_name='ايقونة التطبيق'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='imageOfNotification',
            field=models.ImageField(max_length=1024, upload_to='C:\\Users\\PC\\Desktop\\myProjects\\blockContent\\backEnd\\blockContent/uploads_images/2025-03-08/', verbose_name='صورة البلاغ'),
        ),
    ]
