# Generated by Django 5.1.5 on 2025-03-08 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_child_childuser_alter_customuser_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='ChildUser',
            field=models.ForeignKey(blank=True, limit_choices_to={'userType': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL, verbose_name='اختر الابن'),
        ),
    ]
